apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-postgres
  template:
    metadata:
      labels:
        app: users-postgres
    spec:
      containers:
        - name: users-postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_USER
              value: trickster
            - name: POSTGRES_PASSWORD
              value: 3xtrpsql
#          volumeMounts:
#            - mountPath: "/var/lib/postgresql/data"
#              name: "users-pgdata"
#      volumes:
#        - hostPath:
#            path: "/home/docker/pgdata"
#          name: users-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: users-postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    service: postgres
